# Generated by Django 6.0.5 on 2026-05-30 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='diagnosos',
            new_name='diagnosis',
        ),
    ]
