# Generated by Django 6.0.5 on 2026-05-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    """Alters the status field on Appointment to use TextChoices with predefined status options."""

    dependencies = [
        ('bookings', '0002_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20),
        ),
    ]
