# Generated by Django 6.0.5 on 2026-05-30 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Updates ForeignKey fields on Appointment and MedicalNote to use explicit related_name values."""

    dependencies = [
        ('bookings', '0003_alter_appointment_status'),
        ('doctors', '0005_alter_doctoravailability_options'),
        ('patients', '0001_initial'),
    ]

    operations = [
        # Add explicit related_name for reverse relation from Doctor to Appointment
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor'),
        ),
        # Add explicit related_name for reverse relation from Patient to Appointment
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient'),
        ),
        # Add explicit related_name for reverse relation from Appointment to MedicalNote
        migrations.AlterField(
            model_name='medicalnote',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_notes', to='bookings.appointment'),
        ),
    ]
