# Generated by Django 6.0.5 on 2026-05-30 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['start_date', 'start_time']},
        ),
    ]
